# Generated by Django 2.1.5 on 2019-01-20 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estrutura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordemproducao', models.CharField(max_length=50)),
                ('prazocorte', models.IntegerField()),
                ('prazocaldsolda', models.IntegerField()),
                ('prazousinagem', models.IntegerField()),
                ('prazopintura', models.IntegerField()),
                ('dataEntregaMax', models.DateField()),
                ('dataEntradaSistema', models.DateTimeField(auto_now_add=True)),
                ('dataInicioProcesso', models.DateTimeField(blank=True, null=True)),
                ('dataBaixaCorte', models.DateTimeField(blank=True, null=True)),
                ('dataBaixaCaldSolda', models.DateTimeField(blank=True, null=True)),
                ('dataBaixaUsinagem', models.DateTimeField(blank=True, null=True)),
                ('dataBaixaPintura', models.DateTimeField(blank=True, null=True)),
                ('dataConfirmEntrega', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estruturas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('prazopadraocorte', models.IntegerField()),
                ('prazopadraocaldsolda', models.IntegerField()),
                ('prazopadraousinagem', models.IntegerField()),
                ('prazopadraopintura', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Maquinas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('areaNegocio', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.AddField(
            model_name='maquina',
            name='id_maquinas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='telaPrincipal.Maquinas'),
        ),
        migrations.AddField(
            model_name='estruturas',
            name='id_maquinas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='telaPrincipal.Maquinas'),
        ),
        migrations.AddField(
            model_name='estrutura',
            name='id_estruturas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='telaPrincipal.Estruturas'),
        ),
        migrations.AddField(
            model_name='estrutura',
            name='id_maquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='telaPrincipal.Maquina'),
        ),
    ]
