# Generated by Django 2.1.5 on 2019-02-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telaPrincipal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estrutura',
            old_name='dataInicioProcesso',
            new_name='dataInicioManufatura',
        ),
        migrations.AlterField(
            model_name='estrutura',
            name='dataEntregaMax',
            field=models.DateTimeField(),
        ),
    ]
