# Generated by Django 2.1.7 on 2019-03-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telaPrincipal', '0002_auto_20190210_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estrutura',
            name='dataInicioManufatura',
            field=models.DateTimeField(),
        ),
    ]
