# Generated by Django 2.1.7 on 2019-05-01 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telaPrincipal', '0003_auto_20190325_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyScheduleManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diaeHoraEntrada', models.DateTimeField(auto_now_add=True)),
                ('diaeHoraSaida', models.DateTimeField(blank=True, null=True)),
                ('id_estrutura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='telaPrincipal.Estrutura')),
            ],
        ),
        migrations.CreateModel(
            name='Locais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Setores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='locais',
            name='id_setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='telaPrincipal.Setores'),
        ),
        migrations.AddField(
            model_name='hourlyschedulemanagement',
            name='id_local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='telaPrincipal.Locais'),
        ),
    ]
