# Generated by Django 2.1.7 on 2019-05-05 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telaPrincipal', '0004_auto_20190501_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyScheduleManagementRealizado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diaeHoraEntrada', models.DateTimeField(blank=True, null=True)),
                ('diaeHoraSaida', models.DateTimeField(blank=True, null=True)),
                ('id_estrutura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='telaPrincipal.Estrutura')),
                ('id_local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='telaPrincipal.Locais')),
            ],
        ),
        migrations.AlterField(
            model_name='hourlyschedulemanagement',
            name='diaeHoraEntrada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
