# Generated by Django 2.1.7 on 2019-05-23 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telaPrincipal', '0005_auto_20190505_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyScheduleManagementEmProcesso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diaeHoraEntrada', models.DateTimeField(blank=True, null=True)),
                ('diaeHoraSaida', models.DateTimeField(blank=True, null=True)),
                ('id_estrutura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='telaPrincipal.Estrutura')),
                ('id_local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='telaPrincipal.Locais')),
            ],
        ),
    ]
