# Generated by Django 2.1.7 on 2019-05-24 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telaPrincipal', '0006_hourlyschedulemanagementemprocesso'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HourlyScheduleManagementEmProcesso',
            new_name='HSMEmProcesso',
        ),
    ]
