# Generated by Django 2.1.7 on 2019-06-09 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telaPrincipal', '0008_auto_20190609_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='HSMTarefasGerais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_hsmemprocesso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='telaPrincipal.HSMEmProcesso')),
                ('id_hsmrealizado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='telaPrincipal.HourlyScheduleManagementRealizado')),
            ],
        ),
        migrations.CreateModel(
            name='TarefasGerais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='hsmtarefasgerais',
            name='id_tarefasgerais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='telaPrincipal.TarefasGerais'),
        ),
    ]
