# Generated by Django 2.1.7 on 2019-06-09 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telaPrincipal', '0010_tarefasgerais_sigla'),
    ]

    operations = [
        migrations.AddField(
            model_name='hsmemprocesso',
            name='id_tarefasgerais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='telaPrincipal.HSMTarefasGerais'),
        ),
        migrations.AlterField(
            model_name='hsmemprocesso',
            name='id_usuario',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
