# Generated by Django 2.1.7 on 2019-06-09 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telaPrincipal', '0011_auto_20190609_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hsmemprocesso',
            name='id_tarefasgerais',
        ),
    ]
