# Generated by Django 2.1.7 on 2019-06-09 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telaPrincipal', '0014_auto_20190609_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsmtarefasgerais',
            name='id_hsmrealizado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='telaPrincipal.HourlyScheduleManagementRealizado'),
        ),
    ]
