# Generated by Django 2.1.7 on 2019-06-09 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telaPrincipal', '0016_auto_20190609_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hsmtarefasgerais',
            name='id_hsmemprocesso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='telaPrincipal.HSMEmProcesso'),
        ),
    ]
